version: '3.5'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "TesteProdutosIsthmusSistemas!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data

  produtos:
    image: produtos-teste-isthmus-cleber:latest
    build: 
      context: .
      dockerfile: ./Produtos.Api/Dockerfile
    environment:
      DatabaseProperties__ConnectionString: "Host=127.0.0.1:1433;Username=admin;Password=TesteProdutosIsthmusSistemas!;Database=produtos"
    ports: 
      - "8080:8080"
    depends_on: 
      - sqlserver
