version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "TesteProdutosIsthmusSistemas!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - produtos-network
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data

  produtos:
    image: cleberfbarbosa/isthmus-produtos-teste:latest
    environment:
      - DatabaseProperties__ConnectionString=Data Source=sqlserver,1433;Initial Catalog=produtos;User Id=sa;Password=TesteProdutosIsthmusSistemas!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "35456:8080"
    networks:
      - produtos-network
    depends_on: 
      - sqlserver

networks:
  produtos-network:
    driver: bridge